@SwiftLift.Riders.Api_HostAddress = http://localhost:5067
###

GET {{SwiftLift.Riders.Api_HostAddress}}/build-info
Accept: application/json
x-correlation-id: my-correlation-id

###

GET {{SwiftLift.Riders.Api_HostAddress}}/health
Accept: application/json

###


GET {{SwiftLift.Riders.Api_HostAddress}}/alive
Accept: application/json

###


GET {{SwiftLift.Riders.Api_HostAddress}}/dummy
Accept: application/json

###
