@SwiftLift.Riders.Api_HostAddress = http://localhost:5067
###

GET {{SwiftLift.Riders.Api_HostAddress}}/build-info
Accept: application/json
Correlation-Id: my-correlation-id

###

GET {{SwiftLift.Riders.Api_HostAddress}}/health
Accept: application/json

###


GET {{SwiftLift.Riders.Api_HostAddress}}/alive
Accept: application/json

###


GET {{SwiftLift.Riders.Api_HostAddress}}/dummy
Accept: application/json
#Correlation-Id: 3FCE1EE6-2184-4B91-9EBA-BFE98C7F5339


###
